version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "beta"
  - package-ecosystem: "docker"
    directory: "/app"
    schedule:
      interval: "daily"
    target-branch: "beta"
  - package-ecosystem: "gradle"
    directory: "/app"
    schedule:
      interval: "daily"
    target-branch: "beta"
  - package-ecosystem: "terraform"
    directories:
      - "/infrastructure/app"
      - "/infrastructure/bootstrap"
      - "/infrastructure/infra"
    groups:
      all:
        patterns:
          - "hashicorp/google"
          - "hashicorp/local"
          - "integrations/github"
    schedule:
      interval: "daily"
    target-branch: "beta"
