version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "beta"
  - package-ecosystem: "docker"
    directory: "/app"
    schedule:
      interval: "daily"
    target-branch: "beta"
  - package-ecosystem: "gradle"
    directory: "/app"
    schedule:
      interval: "daily"
    target-branch: "beta"
  - package-ecosystem: "terraform"
    directory: "/infrastructure/app"
    schedule:
      interval: "daily"
    target-branch: "beta"
  - package-ecosystem: "terraform"
    directory: "/infrastructure/bootstrap"
    schedule:
      interval: "daily"
    target-branch: "beta"
  - package-ecosystem: "terraform"
    directory: "/infrastructure/infra"
    schedule:
      interval: "daily"
    target-branch: "beta"
