branches:
  - name: main
    channel: prod
  - name: beta
    channel: dev
    prerelease: true

plugins: [
  [
    "@semantic-release/commit-analyzer",
    {
      "releaseRules": [
        { "type": "build", "release": "patch" },
        { "type": "ci", "release": "patch" },
        { "type": "refactor", "release": "patch" }
      ]
    }
  ],
  [
    "@semantic-release/exec",
    {
      "publishCmd": "make VERSION=${nextRelease.version} ${nextRelease.channel}"
    }
  ],
  "@semantic-release/release-notes-generator",
  "@semantic-release/github"
]
