branches:
  - name: main
    channel: production
  - name: beta
    channel: development
    prerelease: true

plugins: [
  [
    "@semantic-release/commit-analyzer",
    {
      "releaseRules": [
        { "type": "build", "release": "patch" },
        { "type": "ci", "release": "patch" },
        { "type": "refactor", "release": "patch" }
      ]
    }
  ],
  [
    "@semantic-release/exec",
    {
      "publishCmd": "task ENVIRONMENT=${nextRelease.channel} VERSION=${nextRelease.version} release"
    }
  ],
  "@semantic-release/release-notes-generator",
  "@semantic-release/github"
]
