name: analysis-check
description: Checks whether source code analysis is required
inputs:
  commit:
    description: The commit to consider
    required: true
  previous-commit:
    description: The previous commit to consider
    required: true
  ref-name:
    description: The branch name
    required: true
outputs:
  analysis-required:
    description: Whether source code analysis is required
    value: ${{ steps.analysis-check.outputs.analysis-required }}
runs:
  using: composite
  steps:
  - name: Check if analysis is required
    id: analysis-check
    shell: bash
    run: |
      if ${{ inputs.ref-name == 'main' }}
      then
        echo "analysis-required=true" >> $GITHUB_OUTPUT
      else
        if git diff --name-only ${{ inputs.previous-commit }} ${{ inputs.commit }} | grep -E '^(app/src/main/kotlin/|app/src/main/resources/static/assets/css/|app/src/main/resources/static/assets/js/|infrastructure/app/.*\.tf)'
        then
          echo "analysis-required=true" >> $GITHUB_OUTPUT
        else
          echo "analysis-required=false" >> $GITHUB_OUTPUT
        fi
      fi
