version: "3"

tasks:
  init:
    env:
      TF_CLI_ARGS_init: "-input=false -reconfigure -upgrade -backend-config=bucket=terraform-state-{{.GOOGLE_PROJECT}} -backend-config=prefix=common/infra"
    cmds:
      - terraform init

  plan:
    env:
      TF_CLI_ARGS_plan: "-input=false -out=tfplan"
      TF_VAR_artifact_registry_location: "{{.ARTIFACT_REGISTRY_LOCATION}}"
      TF_VAR_artifact_repository: "{{.ARTIFACT_REPOSITORY}}"
      TF_VAR_credentials: "{{.CREDENTIALS}}"
      TF_VAR_firestore_location: "{{.FIRESTORE_LOCATION}}"
      TF_VAR_smtp_server_password: "{{.SMTP_SERVER_PASSWORD}}"
    cmds:
      - terraform plan

  apply:
    env:
      TF_CLI_ARGS_apply: "-auto-approve tfplan"
    cmds:
      - terraform apply
