package be.alpago.website.interfaces.kotlinx.html.style

object EscapeVelocity {

    const val actions = "actions"
    const val alnCenter = "aln-center"
    const val alnMiddle = "aln-middle"
    const val box = "box"
    const val button = "button"
    const val col12 = "col-12"
    const val col12Medium = "col-12-medium"
    const val col12Small = "col-12-small"
    const val col4 = "col-4"
    const val col6 = "col-6"
    const val col8 = "col-8"
    const val container = "container"
    const val content = "content"
    const val copyright = "copyright"
    const val default = "default"
    const val featureList = "feature-list"
    const val featured = "featured"
    const val footer = "footer"
    const val gtr150 = "gtr-150"
    const val gtr50 = "gtr-50"
    const val header = "header"
    const val highlights = "highlights"
    const val highlight = "highlight"
    const val icon = "icon"
    const val image = "image"
    const val impMedium = "imp-medium"
    const val isPreload = "is-preload"
    const val nav = "nav"
    const val pageWrapper = "page-wrapper"
    const val post = "post"
    const val row = "row"
    const val small = "small"
    const val style1 = "style1"
    const val style2 = "style2"
    const val style3 = "style3"
    const val title = "title"
    const val wrapper = "wrapper"
}
